### ISSUE TITLE
JS: sound glitches at the end

### ISSUE THREAD

**Issue by zommerfelds** [HeapsIO/heaps#1067]
There is a very unpleasant sound glitch at the end of sounds in Heaps in the browser. Also, the sounds seems less clear overall compared to the original file.

Checkout the repro here: https://zommerfelds.github.io/heaps-sound-bug/

Tested on Windows on Google Chrome and Microsoft Edge and on Android in Chrome. Checked both with embedded res or PAK file. Tested on 1.9.0 and on the latest git commit.

**Comment by zommerfelds** [comment]
I just tested it in the HL output as well. There it sounds fine. Strangely however, the sound can only be played once. Maybe I should file another bug. See [source code](https://github.com/zommerfelds/heaps-sound-bug/blob/main/src/App.hx).

**Comment by Yanrishatum** [comment]
JS sound driver in general is pretty wonky. It does the job somewhat, however it's severely limited in what and how it can do thing.  (And WebAudio API doesn't help in that regard, as it's centered around audio workers a lot, and Heaps being a single-file-output does not allow us to use them). 
Have you reproduced issue with other sounds, or only with extremely short ones?

**Comment by zommerfelds** [comment]
Length doesn't matter. But I got a new clue! I inspected the sound files where this happens: they have a sampling rate of 44100.

Seems like if I convert to 48000 the sound is fine. Checkout my link again, I uploaded a new version comparing the two.

![image](https://user-images.githubusercontent.com/1260622/162586218-2fd3358e-fc2f-42ac-8dd5-21da7efdc977.png)

**Comment by zommerfelds** [comment]
Actually, scratch that. Even if I export with Audacity in the same frequency the sound is fixed. There is simply something about the original file that Heaps can't process as well as the JavaScript API.

BTW, the sound was generated with https://sfxr.me/.

If anybody is a pro at inspecting WAV files, feel free to take a look at the difference: https://github.com/zommerfelds/heaps-sound-bug/tree/main/www/res

**Comment by edwood-grant** [comment]
Hey @zommerfelds,

I decide to chekc on this, and the cruacial differences between the two file sis the bit depth. 

One is 8-bit:
![imagen](https://user-images.githubusercontent.com/44873757/185731037-5ba3a66a-cf22-4d3e-b7c7-1574317d5197.png)

The other one is 16-bit:
![imagen](https://user-images.githubusercontent.com/44873757/185731050-f3acb4a0-c821-4c24-8015-9ebaf2f03210.png)

Looking at the source, it seems that the conversion of 8-bit WAV files to the webaudio AudioBuffer data is failing because of getting the wrong specification. 8-bit WAV files store their data as unsigned ints, but form 16-.bit onward its is stored on 16 signed ints.

The AduioBuffer data receives data in [-1, 1] range, and Heaps was converting this wrongly because of this iversight in the specification.

There is a PR already ongoing for this, but the workaround for now is to not use 8-bit WAV files, and convert them to 16-bit to aovid artifacts in the playback.

**Comment by zommerfelds** [comment]
Thank you @edwood-grant!
