### ISSUE TITLE
Samples.GpuParticles has errors

### ISSUE THREAD

**Issue by micage** [HeapsIO/heaps#244]
Hello,

I'm quite new to haxe and unable to fix this errors:

```
Mac-Pro:gpuParticles mmm7$ haxe gpuParticles_js.hxml
../../GpuParticles.hx:34: characters 40-52 : h3d.parts.GpuParticles has no field amount
../../GpuParticles.hx:34: characters 66-78 : h3d.parts.GpuParticles has no field amount
../../GpuParticles.hx:48: characters 38-50 : Cannot access private field bounds
../../GpuParticles.hx:61: characters 28-46 : h3d.parts.GpuPartGroup has no field currentParts
../../GpuParticles.hx:63: characters 6-25 : h3d.parts.GpuParticles has no field uploadedCount
../../GpuParticles.hx:64: characters 20-39 : h3d.parts.GpuParticles has no field uploadedCount

```

I looked into `h3d.parts.GpuParticles` and the `amount` field was there and public, fine, so what?
Same with `h3d.parts.GpuParticles.bounds`. Although the syntax `bounds(default, null)` looks strange to me since `h3d.col.Bounds.new()` has no arguments.
But `h3d.parts.GpuParticles.GpuPartGroup.currentParts` is private and shouldn't be accessible by `SampleApp`, right?
Is it ok to put two classes into one file?

You see, I'm just trying to make educated guesses since I just started with haxe.

There are also errors in samples that uses the `addSlider` function, the arguments were mixed up. This I managed to fix. `SampleApp` defines `addSlider` differently than `pbr` for example.

**Comment by Jumblemuddle** [comment]
Do you have the latest version of heaps in haxelib?
I just built the samples on the latest commit (becdc73bbbe1), and this one works fine without any modification.

**Comment by Jumblemuddle** [comment]
You don't by any chance have two copies of the heaps repo do you? (one in haxelib which is old and one which you're running the samples from)

**Comment by micage** [comment]
oh, that's possible. will check this.

**Comment by micage** [comment]
You were right. I installed heaps with haxelib install. It resides in `/usr/local/lib/haxe/lib/heaps`. In my Developper/Tests folder I git-cloned the latest master of heaps. I fixed that by copying the latest version from git into haxe/lib/heaps/0,9,0 folder. There is also a file named `.current` with content "0.9.0" which is not part of the git repository. That procedure does not feel right.

How should I do it?
Stick with the haxelib version and let the git version be?

Now if I build the samples one by one, each at a time there are no problems. But doing it with `haxe all.hxml` it gives me errors like this for every sample:
```
world/world_hl
/usr/local/lib/haxe/lib/heaps/0,9,0/h3d/impl/GlDriver.hx:585: characters 7-15 : Only inline or read-only (default, never) fields can be used as a pattern
/usr/local/lib/haxe/lib/heaps/0,9,0/h3d/impl/GlDriver.hx:621: characters 20-28 : Class<sdl.GL> has no field RGBA8 (Suggestions: RGBA4, RGBA)
/usr/local/lib/haxe/lib/heaps/0,9,0/h3d/impl/GlDriver.hx:642: characters 76-91 : Void should be Int
/usr/local/lib/haxe/lib/heaps/0,9,0/h3d/impl/GlDriver.hx:642: characters 76-91 : For function argument 'format'
/usr/local/lib/haxe/lib/heaps/0,9,0/h3d/impl/GlDriver.hx:649: characters 66-81 : Void should be Int
/usr/local/lib/haxe/lib/heaps/0,9,0/h3d/impl/GlDriver.hx:649: characters 66-81 : For function argument 'format'
/usr/local/lib/haxe/lib/heaps/0,9,0/h3d/impl/GlDriver.hx:840: characters 81-97 : Void should be Int
/usr/local/lib/haxe/lib/heaps/0,9,0/h3d/impl/GlDriver.hx:840: characters 81-97 : For function argument 'format'
```

**Comment by Jumblemuddle** [comment]
I personally don't use haxelib, though I believe you'll need a `.current` file at `/usr/local/lib/haxe/lib/heaps/.current` with content `git`. Then also a folder `git` at `/usr/local/lib/haxe/lib/heaps/git`. The actual project will be located in here.

How did you install heaps? `haxelib git heaps https://github.com/ncannasse/heaps.git`?
If so, running `haxelib update` should do a `git pull` on it.

Anyways, what I personally did was make the samples point to their parent folder's heaps. (Which makes more sense, since the samples _should_ always be built for the version they're located in.)

Apply this [patch.txt](https://github.com/HeapsIO/heaps/files/818346/patch.txt) to your repo (copy into root of project and run `git apply patch.txt`), and it will update the hxml templates to point to their parent heaps as well as add the format library. (The downside of this is that haxelib dependencies need to be manually added to hxml files.)

@ncannasse Would you be alright with those samples' hxml files being changed in this way to always use the version of heaps they're cloned with? If so, I can create a PR, if you'd like.

**Comment by Jumblemuddle** [comment]
@micage Huh, looks like @ncannasse did add heaps to haxelib 12 days ago. (https://github.com/HeapsIO/heaps/issues/106) I wasn't aware of that. That's where your 0.9.0 version came from.
I'd be curious to know if that version is fairly stable, specifically for building the samples.

**Comment by micage** [comment]
@Jumblemuddle  thanks for your git tips. I will try that out.
Do you know if there is a way to get heaps running on Android/iOS?
I wasn't able to compile the hl-samples and also don't know what they are good for.
`openfl test mac` or `openfl test ios` produces a lot of errors in GlDriver.hx complaining about unknown GL constants and also in  LimeStage.hx.

**Comment by ncannasse** [comment]
OpenFL issues are a different thread, I'll close this one since the original problem is fixed :)
