### ISSUE TITLE
hxsl.Dce can't remove all unused vertex params

### ISSUE THREAD

**Issue by EverySteps** [HeapsIO/heaps#247]
hi
look this simple example:
```
var cube:Cube = new Cube();
cube.addUVs();
var t:Texture = hxd.Res.logo.toTexture();
var mat:MeshMaterial = new MeshMaterial(t);
var mesh = new Mesh(cube,mat,s3d);
```

run it,the error : [Fault] exception, information=Buffer stride (5) and shader stride (8) mismatch
i just want use position and uv ,but the normal is not removed by Dce.hx.
i found run top program,the Dec.hx  inputs=[position,normal,uv]
the judge is `while( inputs.length > 1 && !inputs[inputs.length - 1].used ) inputs.pop();`
because uv was used ,so the normal can't remove by Dec.hx.
i think can use this:
`inputs = Lambda.array(Lambda.filter(inputs, function(p) return p.used == true));`

**Comment by ncannasse** [comment]
It's normal that we don't remove inputs because the layout is important so if we have declared (pos,normal,uv) and are only using (pos,uv) we need to keep normal or else we might think the buffer consists of (pos,uv) and thus use normal data in place of UV.

So in heaps you need to have normals if you want to have UV (using the default shader).
