### ISSUE TITLE
hxd.Timer needs some love

### ISSUE THREAD

**Issue by nadako** [HeapsIO/heaps#319]
Subj. [Its fields](https://github.com/HeapsIO/heaps/blob/f62ae28d1372cadaa518b8fb70932554c4c81df7/hxd/Timer.hx#L5-L11) are confusing: can't easily say what means what, why they are public-writeable (or public at all), and the snake_case naming looks foreign.

Also [hxd.App.mainLoop](https://github.com/HeapsIO/heaps/blob/f62ae28d1372cadaa518b8fb70932554c4c81df7/hxd/App.hx#L114-L115) uses hard-coded `60` number instead of `wantedFPS`.

**Comment by Yanrishatum** [comment]
I have to add that for some reason, `hxd.Engine` uses it's own internal timing system. It keeps track of FPS as well. And does it in different manner.
Additionally there's a multitude of places where 60 as fps is hardcoded apart from `App`. Plus `System.getDefaultFrameRate` used a few times, which always returns 60 and cannot be altered. 
I can add documentation to Timer, but I don't understand what `tmod` means exactly. It measures a "percentage" of last tick taking exactly the wanted fps frame time? And why there's `tmoc` and `calt_tmod` if they're basically same? @ncannasse 

Additionally, I would propose next changes:
Introduce deltaT which is not limited by `maxDeltaTime`.
Rename `oldTime` to `timestamp` or similiar.
Make `frameCount` public.
Disallow external writing of exposed values.

Next, the `fps()` function should multiply instead of division, otherwise when at 30fps it would show 120 with target fps of 60. :)
I will as well going to try to remove majority of hardcoded fps values to use `hxd.Timer.wantedFPS`.

**Comment by ncannasse** [comment]
hxd.Timer is quite particular and inherited from flash days.

On desktop with vsync you always get some kind of fixed fps (either 60 or 30 , 20, 15 etc) but on browser/flash you will get varying fps that can vary depending if you suddenly spawn a lot of particles etc. In order to smooth the fps we used to have a slowly evolving fps, hence the difference between "immediate" timer calc_tmod and "smoothed" one tmod.

Regarding the difference between tmod and FPS : I understand it's unusual but tmod is a "normalized" value, so instead of measuring your times in terms of  movement-per-second, you can express them in movement-per-frame-at-wantedFPS , this is particularly useful in 2D pixel games where speeds in terms of pixel per second would be very low.

But I understand this should maybe not longer be the base in Heaps, I'll look at changing that.
