### ISSUE TITLE
Introduce 2D camera

### ISSUE THREAD

**Issue by Yanrishatum** [HeapsIO/heaps#458]
I've noticed a lot of people ask about how to do camera in s2d. Usually people just refer to Beeblerox's [heaps samples](https://github.com/Beeblerox/Simplest-Heaps-Examples/tree/master/13_heaps_camera_scroll). Since it's such a frequent thing people want - it just begs a question on why there is no camera controller for s2d out of the box?
Hence, I propose adding `h2d.Camera` class, but there's much to discuss:

* How exactly camera would affect the scene? Two obvious ways of implementation (both have issues)
  * Beeblerox method: Make camera an Object and add objects it should display as a child. 
Issue:: Additional layer between object and scene, no multiple cameras support.
  * Make camera manipulate Scene position. 
Issues: Most likely requires a lot of work on Scene/Layers to account for it's transformation, no multiple cameras support. 
* Should there be support for multiple cameras? (Picture-in-picture, etc)
* Should camera support post-process effects?
* Should camera allow for rotation and scale?

**Comment by ncannasse** [comment]
Yes I agree with you on this, actually got the same thoughts when reading Discord.

I would not have a Camera applied directly on or modify the Scene position because you might want to add other not scrolled elements like your UI on top of it, so maybe having an Object (extending Layers?) and put things "into the Camera" (as children) would work good enough?

Also, Camera should automatically adapt to scene resize, so it is needed to check scene width/height at each sync. Finally I would add the ability to "smooth" camera movement over time.

Post processes can already be done by adding filters on Camera object (or any Object actually)

Scaling the Camera with scaleX/Y should zoom in/out so it will be taken into account. Same of rotation I guess.

**Comment by Yanrishatum** [comment]
And what about multiple cameras support? Simplest use-case would be split-screen. Duplicating object tree obviously is not an option in that case. 
Additionally that raises a question of parallaxing objects. (Example: Multiple backdrops that scroll past at different speeds when camera moves).

**Comment by ncannasse** [comment]
If you put a Camera inside a Mask you can clip the result and have many cameras.
As for parallax, this should be handled manually by scrolling manually the objects relatively to the camera position.

**Comment by ncannasse** [comment]
Uhm. Well we could have a "content" reference that can be set to display instead / "under of" the children list. But that would require a double sync() to update the matrixes , which might play twice the animations etc. So maybe let's forget about it for now? :)

**Comment by ncannasse** [comment]
Closing in favor of #459
