### ISSUE TITLE
hxd.res.Font support for Hashlink

### ISSUE THREAD

**Issue by kevansevans** [HeapsIO/heaps#461]
https://github.com/HeapsIO/heaps/blob/master/hxd/res/Font.hx

As title says. Can't use anything besides default for Hashlink target.

**Comment by Yanrishatum** [comment]
This function provides ability to rasterize outline (TTF/OTF) fonts at runtime (`FontBuilder` class). There is no Hashlink support because there is no native capabilities to do so on that target (for now at least). 
Please refer to this wiki page on how to add your own fonts: https://github.com/HeapsIO/heaps/wiki/Text
To delve into details: To add support of TTF/OTF to Hashlink, there should be either Haxe-backed or native-backed library that would handle the rasterization. `FontBuilder` uses native approach on each target (Using TextField -> BitmapData rendering on Flash, drawing text on canvas for JS and Cairo for Lime).

**Comment by ncannasse** [comment]
You can use hxd.res.BitmapFont instead, see https://heaps.io/documentation/text.html
