### ISSUE TITLE
Tiled format support out of date

### ISSUE THREAD

**Issue by Eiyeron** [HeapsIO/heaps#478]
Hello, I'm chekcing out some parts of the lib and am noticing the Tiled support is a bit out of date.
I guess that because CDB is starting to become something pretty interesting and gathers leverage here, I suppose Tiled won't be supported as well as before.

So the helper class lags behind the current version of the file structure (notably lacks stuff like group layers, tile collisions, etc...)

Should it be kept, even though it lags behind features, should it be deprecated, should it be moved to a small helper library?

(I'm also wondering how to properly make the class evolve. I have my own implementation based on the .json format that does a bit more than the library's class (like generating a collision mesh), but it's probably a bit too specialized?)

Have a nice day.

**Comment by Eiyeron** [comment]
I saw your library and I appreciate the work you did in it, I might switch to it for my own projects.

Depending on what the PR offers, it might still be a good upgrade if you get to allow loading tilesets or images from a local path against the tiled file. I'm still scratching my head over this problem.

For the multiple tileset support, the worst-case scenario I'm thinking of is having n-`TileGroup` per layer, as each can only support one tilesheet at one time. It might get in the way of other rendering systems than just the regular top-to-bottom left-to-right orthogonal map though.

And for collision meshes, yeah, that's definitely way to specialized for heaps. It has most of the tools needed for the basic cases (clipper and a triangularization routine -haven't found a good way to process meshes with holes without filling them :°)

**Comment by Yanrishatum** [comment]
Initial PR plans are pretty barebones: Parse TMX, handling of tileset loading (e.g. load associated images and pass them as an array of `h2d.Tile`), TSX support (I use tsx for quite some time, because when you use tilesets with parameters and even collisions - keeping them in-sync between all maps is crucial).
Renderer require some sophisticated code, because it have to handle render-order, as well as being capable of rendering in all supported modes.

**Comment by Eiyeron** [comment]
Sounds pretty promising, I'm looking forward progress in this PR!

**Comment by 7sharp9** [comment]
Yeah I hit this too, following the tiled map example it was a bit tricky to get tiled to output in a format the heaps could actually read.

**Comment by Yanrishatum** [comment]
While stock heaps do not provide proper Tiled support (and I'm not going to reimplement it for Heaps - I already have format-tiled library), I have external library support in [heeps](https://github.com/yanrishatum/heeps). As for rendering layers, there is an example basic layer renderer in [format-tilet](https://github.com/Yanrishatum/haxe-format-tiled/blob/master/tiled/TileLayerRenderer.hx) which is pretty easy to hook for Heaps. It's implementation is not full, and not really optimized, but it should do for a start or as a reference on how to render it.
If you want more in-depth support of Tiled, I suggest creating an issue in Heeps library describing specific features you are interested in.

**Comment by Yanrishatum** [comment]
If you have any questions regarding setting all this up, you can ping me on Haxe discord (under same `@Yanrishatum` handle), I'll try to help if able. Settings up Tiled rendering is actually pretty easy when using format-tiled, especially if you already know in what way you plan to use Tiled (aka only square tiles, no overlap, only one tileset or multiple, specific size, etc)

**Comment by 7sharp9** [comment]
I think I could only get it to work when I set the format of tiled to not use any base64 compression(xml format is the only one), then also export it to json.
@ncannasse  I only decided to use Tiled as that what was described in the docs, is there something else thats more common with Heaps.io?   Perhaps that should be detailed in the docs instead.

**Comment by sangohan** [comment]
presumably, http://castledb.org/#level is better supported in heaps.io than tiled.

**Comment by Yanrishatum** [comment]
@ncannasse It's not that it is no longer works. It is just Tiled format is extremely more advanced than that, with later versions supporting grouped layers, infinite maps (e.g. chunked map data), object templates, imageset tilesets (actually tilesets in general), image layers, visual offset, object/layer properties, object hitboxes, tile animations, etc. What is present in Heaps is feature list of Tiled of early versions many years old and does not do this powerful editor service. (Just tate a look at [Data.hx](https://github.com/Yanrishatum/haxe-format-tiled/blob/master/format/tmx/Data.hx) that showcases how advanced this format actually is.)
If someone today will try to utilize this built-in support - it won't be pleasant experience, because pretty much all of long-existing features of Tiled are not supported, not to say features of Tiled 1.0 onward. 
I already did a PR that introduced integration of standalone library that contains extensive and almost full coverage of the Tiled format (up to 1.2), but since adding optional dependencies seem to be looked down upon, I **personally** would suggest removing this poor integration outright as to not confuse people with it's lackluster feature list.

**Comment by ncannasse** [comment]
@Yanrishatum I'm fine with removal. But I think we should provide a tutorial somewhere in Heaps doc to use your Tiled extension. Would you like to contribute it? Could be in the `Tools/Tiled` section

**Comment by Yanrishatum** [comment]
My Tiled integration is not exclusive feature of heeps library thought. This extension library adds a deal of other classes that are not fit for stock Heaps (as well as brutally hacks into base classes to add features), and Tiled support is only one of such things. I've made an experimental layer renderer, but it's far from being usable easily (due to lots of work required to make it support all rendering modes), and apart from this and access from Res there's not much of integration provided.

**Comment by thejustinwalsh** [comment]
The integrated support is serving my needs just fine. The docs could use an update on what is or isn’t supported and a disclaimer could be added with links to better implementations.

I understand that the format allows for many more features than are currently supported, however sometimes you simply just need to load up an array of tiles in layers and manage the rendering of the layers yourself.

I would be willing to build a sample that includes a tiled tmx file and shows how to render what comes out of it, if it casts my vote for keeping the basic support around.

**Comment by 7sharp9** [comment]
I think removing it is a bad idea, out of box functionality of tiles is a
good feature to have, especially when it probably just needs a little
tweaking.

**Comment by ncannasse** [comment]
A sample was provided with definition of format limits, closing this for now.
