### ISSUE TITLE
Lime library dependency in LimeStage.Keyboard

### ISSUE THREAD

**Issue by mepsoid** [HeapsIO/heaps#486]
When I'm trying to use constants for key codes described in `hxd.impl.LimeStage.Keyboard` class, compiler warns `LimeStage.hx:209: characters 38-53 : Type not found : lime.ui.KeyCode`.

Heaps version 1.5.0, Haxe version 4.0.0

**Comment by mepsoid** [comment]
`hxd.Key` is incomplete, for example it doesn't contain 187 or 189 key codes. If `Keyboard` class not used for heaps project building it can be excluded fron library at least to not duplicate constants.

**Comment by Yanrishatum** [comment]
Then create an issue (or even PR) about lacking key codes, maybe? ;)
To explain why these classes are present: Lime backend is not officially supported because nobody maintains it. What is present although - already implemented partial support to Lime which have no guarantees to work. Hence, `hxd.impl.LimeStage.Keyboard` _is_ used, but only if you use Lime backend. Same as classes that tied for HLDX, HLSDL and JS targets.
