### ISSUE TITLE
[Proposal] Improve `s2d.Scene.setFixedSize`

### ISSUE THREAD

**Issue by Yanrishatum** [HeapsIO/heaps#524]
Given how Heaps garnered interest of 2D devs, it's appropriate to improve some aspects of how scene acts. Currently `setFixedSize` stretches scene contents up to screen size according to internal resolution.
I propose adding `FixedSizeMode` enum, that would include:
- `Stretch` - will behave as now and will be a default.
- `KeepAspect` - will preserve aspect-ratio of the fixed size. Will shift X/Y depending on window size.
Most useful, because most likely people want to keep aspect ratio when screen is resized for majority of games.
- `KeepPixelSize` - same as `KeepAspect`, but will use integer scaling as long as window size > internal resolution.
Will be useful for pixelart games in case developers don't want to stretch pixels (and make them look ugly) even if aspect ratio is preserved.
- (optional) `PreserveArea` - act as `KeepAspect`, but instead of modifying x/y will change width/height to fill entire screen while keeping fixed size "frame".
Avoids letterboxing.

Changes are:
- `public var fixedSizeMode:FixedSizeMode`
- Optional parameter `mode` for `setFixedSize`.
- Actual logic on resize and changes of size mode.

And for clarity, from now on, when I add `[Proposal]` to issue title, I mean that I will implement proposed feature myself if approved.

**Comment by ncannasse** [comment]
When doing pixel art it's actually quite particular because you might want to either prioritize the wanted height or the wanted width depending on your gameplay. Also, depending on the gameplay you might prefer to have the pixel ratio being rounded up or down.

So while I think KeepAspect would be useful, I'm not sure either about the X/Y shifting, as you don't want for instance someone resizing a window with H > W to suddenly have a 90 degrees rotation applied.

**Comment by Yanrishatum** [comment]
X/Y shift is to center Scene on the screen.
E.g. for `1920x1080` screen size and fixed size of `800x600`, it would use `1.8` zoom (lowest from 2.4/1.8) with `1440x1080` size, and `x = 240`. And `KeepPixelSize` would just change x/y to center it on the screen because this resolution does not fit the screen more than at 1x. Plus adding more possible enums won't be much of an issue once implemented.

**Comment by RobertBorghese** [comment]
Would absolutely love to see this. 

"KeepAspect" is the expected behavior of most games outside of fullscreen, so at the bare minimum it would be nice to at least see it become a built-in option. Along with the window features I've been exposing in Hashlink, this would bring Heaps' support for windowed games up-to-snuff with what you would expect from most desktop game engines. Hopefully this conversation can be revived so we can see that pull request happen. ^^

**Comment by Yanrishatum** [comment]
@RobertBorghese I tinkered with implementing it a bit, and it seems it will require quite a lot of changes in RenderingContext implementation. It needs way more changes than I anticipated, and so far I postponed implementing it to later date (I will get to it eventually, because it's one of the features we'd need during development, but it isn't top priority)
