### ISSUE TITLE
h2d.Graphics doesn't update every frame?

### ISSUE THREAD

**Issue by ratkingsminion** [HeapsIO/heaps#529]
```haxe
import h2d.Graphics;

class Main extends hxd.App {
	var gfx:Graphics;
	override function init() {
		gfx = new h2d.Graphics(s2d);
		gfx.lineStyle(2, 0xffff00);
	}
	override function update(dt:Float) {
		gfx.drawCircle(Math.random() * s2d.width, Math.random() * s2d.height, Math.random() * 40 + 20);
	}
	static function main() {
		new Main();
	}
}
```

This code does not display a new circle every frame, even though it should. HTML5 target.

**Comment by Yanrishatum** [comment]
Elaboration:
It seems that `h2d.Graphics` upload buffers only when current one overfills, and never updates current underfilled buffer, even if new data is available.
Probable solution would be uploading data to last buffer if new vertices were added since last `sync()` call. 
Also this issue reproduce on Hashlink as well, not only HTML5.
