### ISSUE TITLE
pointer/mouse lock support

### ISSUE THREAD

**Issue by Antriel** [HeapsIO/heaps#568]
I see there's some old support for flash, but would be nice to have it supported across the targets.

**Comment by Yanrishatum** [comment]
To expand:
By pointer/mouse lock support there basically need to be 2 different modes:
1. Hide cursor and "lock" it inside game allowing free movement for use-cases like free 3D camera movement in first-person.
2. Just lock cursor on window borders. This is really useful for RTS games, where moving mouse to the border of the screen in order to move camera. As a person with multiple monitors - getting mouse outside of the game window during action and accidental focusing of other app is extremely frustrating.
Ideally, both should be boolean on `hxd.Window` and switched at any time.

For HL: Both should be possible on SDL and DX.
For JS: From my knowledge, first one is possible with (Pointer Lock API)[https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API], however I don't think second one is implementable.

**Comment by Antriel** [comment]
Regarding JS:
As you say the first one (hide cursor and lock it) works. The cursor hiding is automatic and not changeable afaik.
For locking on borders a custom simulated cursor could be used with the normal lock, but that does bring issues of its own (like not being able to use DOM elements with the cursor without controlling their state manually).

**Comment by ncannasse** [comment]
Yes, the two should be good as long as the platform supports it.
As for pointer lock, I would however allow to enter/leave this state, such as:

window.lockPointer(function(dx,dy) // mouse offset event)
window.unlockPointer();

Because when you are pointer locked, you don't get any other kind of mouse events anymore, and mouse position should be set to (-1,-1) to disable all hovers etc.

**Comment by Yanrishatum** [comment]
SDL:
For pointer lock: https://wiki.libsdl.org/SDL_SetRelativeMouseMode
For window lock: https://wiki.libsdl.org/SDL_SetWindowGrab

DirectX/Win:
This one is tricky, because it is recommended to use [raw input](https://docs.microsoft.com/en-us/windows/desktop/inputdev/raw-input) when locking pointer (instead of `WM_MOUSEMOVE`), because if user swings mouse, it can reach the edge of the screen and lead to inaccurate mouse movement.
Without raw input, however: [SetCursorPos](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-setcursorpos) and [ClipCursor](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-clipcursor)

Things to consider: Heaps should automatically unlock and re-lock mouse when game window loose/gain focus.

JS: As mentioned above, [Pointer Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API), but confining mouse to canvas with native methods is not possible, and as mentioned - can be workarounded by (hacky) approach of manually rendering mouse cursor and tracking mouse position virtually.

**Comment by Yanrishatum** [comment]
I started works on PR introducing pointer API and there are a few questions.
First is naming convention. `mouseLock` property will be deprecated in favor of `lockPointer` / `unlockPointer`. But I'm unsure on how to name mouse constraint. `clipMouse`, `windowLock`, something else?
Second is flash. From what I see, flash is the only target that have pointer lock support, but does it in different manner. Should it be updated to match other targets or I can just ignore it?
Third is `mouseX/mouseY` positioning. I feel like it's worth making ability to manually manipulate it when pointer is locked, allowing usage of Interactives in that mode. Clear use-case - first-person interaction with Interactive objects when putting virtual cursor to the center of the screen. Also for -1/-1. Wouldn't it trigger on Interactives that under that position? Using `Int.MAX_VALUE` (or min value) would be more safe.

I already implemented JS target, but not sure how to handle some of the specifics due to it's nature.
I plan to automate disabling both modes when game looses focus (and re-enable them when focuses), but unsure on how to handle it on JS, because pressing escape will unlock mouse. Right now I re-lock mouse whenever user clicks on canvas (onMouseDown). That leads to another API question - maybe add `onCancel` callback for `lockPointer`? Called either when unlocking, loosing focus or changing lock callback. In that case there will be no automation of re-locking, but there will be more control on when mouse should be locked.

**Comment by ncannasse** [comment]
> First is naming convention. `mouseLock` property will be deprecated in favor of `lockPointer` / `unlockPointer`. But I'm unsure on how to name mouse constraint. `clipMouse`, `windowLock`, something else?

mouseWindowLock ?

> Second is flash. From what I see, flash is the only target that have pointer lock support, but does it in different manner. Should it be updated to match other targets or I can just ignore it?

Updated is better if it fits.

> Third is `mouseX/mouseY` positioning. I feel like it's worth making ability to manually manipulate it when pointer is locked, allowing usage of Interactives in that mode. Clear use-case - first-person interaction with Interactive objects when putting virtual cursor to the center of the screen. 

Yes, we started doing this for emulating tooltips trigger when using pad control, see `SceneEvents.enablePhysicalMouse` and `SceneEvents.mouseCheckMove` but maybe better discussing this as separate PR?

> Also for -1/-1. Wouldn't it trigger on Interactives that under that position? Using `Int.MAX_VALUE` (or min value) would be more safe.

Sure

> I already implemented JS target, but not sure how to handle some of the specifics due to it's nature.
> I plan to automate disabling both modes when game looses focus (and re-enable them when focuses), but unsure on how to handle it on JS, because pressing escape will unlock mouse. Right now I re-lock mouse whenever user clicks on canvas (onMouseDown). That leads to another API question - maybe add `onCancel` callback for `lockPointer`? Called either when unlocking, loosing focus or changing lock callback. In that case there will be no automation of re-locking, but there will be more control on when mouse should be locked.

Seems good to me this way.

**Comment by agdt3** [comment]
I don't want to bug you guys, because you're all clearly busy, but is there a way to help with this? I'd like to be able to have an FPS camera with a locked pointer, but because window hooks into sdl primitives, it seems impossible to implement outside of the core library.

Technically, if the dev could set a custom window subclass as the main window, they could override the relevant methods and implement it themselves, but I don't quite see a way to do that either.

Technically even releasing this in parts (my preference is sdl first, obviously), would be great.

Cheers.
