### ISSUE TITLE
[Discussion] textBaseline feature

### ISSUE THREAD

**Issue by Yanrishatum** [HeapsIO/heaps#572]
From discussion in Discord, there was a suggestion that Text may benefit from `textBaseline` support. Worth discussing if it's something useful.

For reference: https://www.w3schools.com/tags/canvas_textbaseline.asp
![pic](https://www.w3schools.com/tags/img_textbaseline.gif)

> Ghouly The Ghost 👻🤙Today at 21:19
> It just makes relative positioning smoother. Instead of always having to reference text height ( which I have complaints about ) you can just decide a y position and just tic below the point or whatever your choices are
Cognitive overhead about where the text is rendered is simply reduced

Implementing it would allow for easier Text usage in certain cases, because aligning it vertically would take less effort. I can take up on implementing it, but does it worth it? I see potential issues with `h2d.Flow` (e.g. `getBoundsRec` will need to set `y` as well when `forSize = true`)
Pros/cons?

**Comment by ncannasse** [comment]
Flow does not play well at all with elements that have negative x/y (top/left), it's done on purpose so we can have offsets being done on the tile for instance instead of by tweaking everytime the bitmap alignment.

And having textBaseLine without Flow support surely does no seem very interesting.

I would vote a no for this.

**Comment by Yanrishatum** [comment]
A few weeks passed and nobody seem interested in this feature, closing.
