### ISSUE TITLE
[RFC] Per platform converts

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/heaps#613]
I'm thinking about ways to setup platform-specific encoding of images, so we can use DXT or other GPU-friendly formats where it matters. This should also solve the setup of WAV conversions, and allow more custom setup to be added.

In order to allow global rules that can be overridden based on a per-directory or per-file basis, I think we should reuse HIDE props.json files.

For instance a toplevel `res/props.json` would be like that:

```json
{
  "fs.convert" : {
        "wav" : "ogg",
        "png" : "dxt5",
        "jpg" : "dxt5"
  }
}
```

Then these rules can be overriden in a subdirectory:

```js
// in res/characters
{
  "fs.convert" : {
        "png" : "dxt1",
        "^*texture\\.png" : "", /* no convertion occurs */
        "myspecifictexture.png" : "dxt5"
  }
}
```

Rules Filter Format (by order of ascending priority):
 - if [a-z]+ : an extension (case insensitive)
 - if starts with ^ : a regexp (will apply to all subdirectories as well)
 - either : a specific file name (will apply to all subdirectories as well)

*Note:* I choose not to allow several extensions with "png,jpg" because then overriding only "png" in a subdirectory would create { "png,jpg", "png" } configuration which is then subject to order-of-fields priority which we should avoid.

Rules Value Format:
- `""` : disable convert
- `"name"` : name of the convert used

**Configurations:**

Different convert configurations can be made, for instance we could have a `ios` configuration that uses specific sections:

```js
{
  "fs.convert" : { ... }, // all configurations
  "fs.convert.default" : { ... }, // default configuration only
  "fs.convert.ios" : { ... }, // ios configuration only
}
```

- add a configuration to hxd.Res.initEmbed/Local
- allow to create a hxd.fs.LocalFileSystem with a specific configuration
- pak builder, optionally specify a configuration to build the pak file

**Converts:**

Converts should register themselves as available conversion from one or several extensions to one or several formats (for instance `["png","jpg"] => ["dxt1","dxt5"]`). Each output format should also have a string describing it (for display in HIDE) with parameters description if applies (see below)
 
Custom converts should be compiled as part of the program (or for HIDE loaded as plugins). HIDE will allow to set convert rules for specific files directly on File Tree and some components (texture viewer) for the different available configurations (looking at configurations declared in toplevel props.json).

**Composition and parameters:**

More complex conversions processes can be performed, for instance:

```json
{
  "fs.convert" : {
          "texture.png" : { "convert" : "resize", "width" : 1024, "then" : "dxt1" }
  }
}
```

Rules Value Format (when value is an object):
- `convert` : the converts used
- `then` (optional) : another convert rule value (can recurse)
- `priority` (optional) : give higher priority for the rule (in case of clashing regexps)
- other fields : parameters passed to the convert

In order to guarantee that changes in parameters are reflected, the output tmp file includes all parameters names and values:
- `texture.png` is converted to `.tmp/texture.png.width_1024.resize`
- `.tmp/texture.png.width_1024.resize` is then converted to `.tmp/texture.png.width_1024.dx1` by second convert

**Converts with multiple files:**

A convert should be able to tell if it outputs multiple files. For instance if a file is in `res/path/something.ext` and is converted to extension `out` these files will be placed there: `/res/.tmp/path/.meta/something.out.<name>`

 * Before converting, all `.meta/something.out.*` are removed
 * Convert have helper functions to write these "meta" files
 * All file systems will lookup these files and handle them as normal files
 * add a `getMeta(name) : Any` and `getMetas() : Array<Any>` to hxd.res.Resource to give access to this meta file

**Converts on Directory:**

A convert can also be made on a directory, which needs to have an extension and a convert attached to it using props.json.

TODO : how to make sure that the directory is excluded from pak/fs listing?

**Comment by ncannasse** [comment]
Ping @trethaller @D0pu @Yanrishatum

**Comment by Yanrishatum** [comment]
Regarding file name, I would also add ability to store heaps-specific configuration files in `.heaps` folder as to not interfere with project assets. It's unlikely that there would be `props.json` in root, but it probably worth separating heaps-specific configuration from regular assets.
There also need to have streamlined way to enable/disable custom convert configurations. For example `convert-production`. Something like `-D` compilation flags would suffice (`-D convert-production`)?

Also while we're at topic of Converts, there's one thing that I was finding a bit annoying - inability to output multiple files, as Convert currently is strictly one input -> one output. (well, technically it's possible to use multiple inputs, but it's via FS access). 
Example use-case: In heeps I have Convert that automatically converts gif files to png spritesheets and also generates frame metadata, and then custom Resource reads both to generate `Animation` instance. Because Convert have to split file into 2, I had to store png not in .tmp directory, but rather nearby the gif file, which is not optimal. I'm not sure how to better implement such a thing, but I see 2 possible ways:
* Convert can also return list of extra generated files, which then added to `Res.` pipeline and strictly accessed via `.tmp` folder. 
* Add hidden file entry to FS, and allow loading it via `Loader.loadTmp`. 

And on top of that: folder-wide Convert is another thing I'm looking at. 
Use-case: Automatic compilation of atlas files for UI (those files used for s2d via Tiles, so it doesn't matter if they are in one file or a bunch of separate ones. And having them in single texture more optimal, while using separate files is more convenient for development)
However it would complicate the convert pipeline a lot, as `times` will have to account that Convert rely on multiple files. 

Those are kinda outside of this discussion scope, so I can just open issues regarding each of that ideas later separately.

**Comment by ncannasse** [comment]
- HIDE already uses props.json files so I prefer to keep this standard

- for convert configuration, we could have a `-D heaps-default-convert=<value>` to replace the `default`

- regarding multiple files output : we are already in the process of adding a new feature which is the handling of .meta files for resources, more on this in my next message

- automatic conversion of folder : this could be done with a .altas file (that would list options to build it) and a custom convert that would generate the actual atlas. Then it would require either to name the directory with a starting dot so it's ignored by FileSystem or by adding a new "fs.exclude" section in props.json to exclude some files/folders from pak

**Comment by ncannasse** [comment]
Edit : I have updated the props.json format:
- introduce a toplevel "fs" object to list convert but also excludes etc.
- change the way we deal with multiple configurations, by allow a common config + override of specific configs

**Comment by ncannasse** [comment]
Edit : I have added a section regarding Converts with multiple files output

**Comment by ncannasse** [comment]
While we're at it, any suggestion for a better name than "convert" ? There's a file "preprocessor" but I don't like it very much either as it has some other meaning.

**Comment by Yanrishatum** [comment]
* Since subfolders allow for overriding of convert list, how it is supposed to be handled? Straight on  replacement or merge?
* `fs.exclude` is actually reasonable, because `res` may contain extra data that shouldn't be bundled in pak files for example. Also if it probably need to support same rules of configs, e.g. `fs.exclude.ios`.
* `.meta` approach: I'm pretty fine with it, as long as Convert can store those meta files in just one call (e.g. `addMeta(name, bytes)` and I think `Resource` should be able to provide a list of meta file names.
* Naming: Well, my only ideas are "ResourceProcessor" and "Baker"/"AssetBaker" (as in asset baking, like "shadowmap baking"), but later sounds silly as heck.
* `.atlas`: While that approach have it's merits, it may not be as useful if there isn't full data separation (like `res/ui/.graphics` separate from `res/ui/configs`, which would have name-matching files, and be more logical to be together in same folder, but due to such approach - it's not possible)

**Comment by ncannasse** [comment]
.atlas : maybe we should have the notion of a "directory" convert, so you would have a directory named `sprites.altas` and it would be converted into one or several files with the convert.

**Comment by ncannasse** [comment]
The branch #614 is ready for review.
Current implements the whole spec except "Converts with multiple files" and "Converts on Directory" sections

**Comment by ncannasse** [comment]
Branch has been merged and documentation is available here:
https://github.com/HeapsIO/heaps/wiki/Resource-Baking
