### ISSUE TITLE
Automatic z-sorting troubles in default alpha pass in default forward rendering.

### ISSUE THREAD

**Issue by lusius** [HeapsIO/heaps#623]
I have a case where two object sharing the same material (same texture etc) are on two opposite sides of a another transparent object.

ObjectA.z = -1.0
ObjectB.z = 0.0
ObjectC.z = 1.0

ObjectA + ObjectC are sharing material. This i believe is causing (even if they aren't sharing material) a problem with z-sorting. They are sorted perfectly fine by getSort() but then in h3d.pass.Default() when sortPasses=true, the sorting in Default.draw() destroys the rendering order and the object are rendered again in the wrong order.

A clear solution would be just to either with privateAccess set the sortPasses to false or create my own renderer. Or make the sortPasses in h3d.pass.Default public.

I'm asking this because I want to know the reason behind this sorting in draw stage, since it literally can destroy the alpha sort and what your suggested solution is.

**Comment by lusius** [comment]
platform target js

**Comment by ncannasse** [comment]
Usually you will first draw all opaque objects (sometimes front-to-back to reduce overdraw) then draw transparent objects sorted back-to-front. That is the default rendering that we use in Heaps and it works in most of the cases.

You can use a custom render by extending the base renderer and setting the `s3d.renderer` in order to have your own way to deal with transparent objects.

**Comment by lusius** [comment]
Yes I know this, and this is why I'm adressing the issue. The ordering is perfectly fine until the Default pass sorters them by material _again_ after doing z-sorting back to front.

This is why I'm asking.

**Comment by ncannasse** [comment]
Sorry I mistake the actual issue, will look into it once more.
