### ISSUE TITLE
Regression in onOver

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/heaps#625]
The following example no longer works as intended : `f2` is never traced.

```haxe

class Main extends hxd.App {

	override function init() {
        var f = new h2d.Flow(s2d);
        f.backgroundTile = h2d.Tile.fromColor(0xFF0000);
        f.padding = 20;

        var f2 = new h2d.Flow(f);
        f2.backgroundTile = h2d.Tile.fromColor(0x0000ff);
        f2.minHeight = f2.minWidth = 100;

        f2.enableInteractive = true;
        f.enableInteractive = true;

        f.interactive.onOver = function(_) {
            trace("f");
        }
        f2.interactive.onOver = function(_) {
            trace("f2");
        }
	}

	static function main() {
		new Main();
	}

}
```

ping @Yanrishatum

**Comment by ncannasse** [comment]
Ref @trethaller

**Comment by Yanrishatum** [comment]
That's actually an expected behavior. Because when setting `enableInteractive`, it adds Interactive like that:
https://github.com/HeapsIO/heaps/blob/7261f2123b6a07ea9818569bf2a4858ac5b37ef1/h2d/Flow.hx#L563-L565
And in the sample code it results in a tree like that:
```
f
|- f2
|  |- f2.interactive
|
|- f.interactive
```
And obviously, due to that, `f.interactive` always grabs mouse, because it's higher than `f2.interactive` in it's tree hierarchy. Fix would be using `addChildAt(interactive, 0)` as it's done with `backgroundTile`:
https://github.com/HeapsIO/heaps/blob/7261f2123b6a07ea9818569bf2a4858ac5b37ef1/h2d/Flow.hx#L585-L587

And "users have to fix it themselves" solution would be to move `f.enableInteractive` before actually adding any children to it.

**Comment by ncannasse** [comment]
Right, the bug is that the flow should handle the interactive in a similar manner to background, which is adding at index 0.

**Comment by Yanrishatum** [comment]
Another precaution required at `Flow.addChildAt`: https://github.com/HeapsIO/heaps/blob/7261f2123b6a07ea9818569bf2a4858ac5b37ef1/h2d/Flow.hx#L453-L455
As it will need to do same check for `if (interactive != null)`

**Comment by ncannasse** [comment]
Yes, I'm looking into it atm
