### ISSUE TITLE
hlsdl does not correctly set custom mouse cursors

### ISSUE THREAD

**Issue by infidel-** [HeapsIO/heaps#650]
When the cursor bitmaps are loaded from PNG files instead of being generated.

I have to following function:
```
      hxd.System.setCursor = function(cur)
        {
          if (cur == Default)
            hxd.System.setNativeCursor(atlas[cursor]);
          else hxd.System.setNativeCursor(cur);
        }
```

with atlas defined as:
```
public var atlas: Array<Cursor>;

...

      for (i in 0...4)
        {
          var r = hxd.Res.load('graphics/' + i + '.png').toImage();
          var tmp = r.toBitmap();
          var cursor = Custom(new CustomCursor([ tmp ], 1, 0, 0));
          atlas.push(cursor);
        }
```

Whenever I need to dynamically change the cursor I call System.setCursor(atlas[xxx]);
This works fine on JS and hldx but not hlsdl. In the latter case the custom cursor is set once and is not changed on later calls.

The problem is even more specific. I've used "cursor" sample from heaps samples as a base and setting custom cursor works fine in hlsdl mode there. Through the trial and error I've found that it's because the cursor bitmaps are generated there. The following code allows correct cursor switching on setCursor() call in hlsdl:

```
      for (i in 0...4)
        {
          var defOverride = new hxd.BitmapData(10, 10);
          var col = 0xffff0000;
          if (i == 1) col = 0xff00ff00;
          else if (i == 2) col = 0xff0000ff;
          else if (i == 3) col = 0xff00ffff;
          else if (i == 4) col = 0xffff00ff;
          defOverride.line(0, 0, 5, 0, col);
          defOverride.line(0, 1, 0, 5, col);
          defOverride.line(0, 0, 10, 10, col);
          var overrideCursor:hxd.Cursor =
            Custom(new hxd.Cursor.CustomCursor([defOverride], 0, 0, 0));
          atlas.push(overrideCursor);
        }
```

**Comment by trethaller** [comment]
Thanks, interesting, we've had some weird glitches with custom cursors on SDL and were suspecting a memory corruption, I may have to look at this in the coming weeks

**Comment by Yanrishatum** [comment]
I've tried to reproduce you issue, and honestly could not. Custom cursors work as expected for me. Could you provide more detailed reproduction sample? E.g.:
Png files you use to create cursor (ones I used seem to work just fine)
In what conditions you switch cursor and how (Interactives? Custom calls? Something else?)
![cursor_bug](https://user-images.githubusercontent.com/1061373/69498978-de2a0800-0efe-11ea-81c3-82ce1a40bff0.gif)
I used same code snippets you provided to populate cursor atlas and set it.

**Comment by infidel-** [comment]
Here's a test code I've made from the project with compiled binaries and mouse png:
[mouse.zip](https://github.com/HeapsIO/heaps/files/3887881/mouse.zip)

On DX (and JS, too) the cursor changes every second. On SDL it doesn't.

Currently I'm using HL 1.10, Heaps Git and Haxe 4.0.2.

**Comment by Yanrishatum** [comment]
After a bit of debugging I concluded that is not a bug. That is a very much expected result, because you are setting cursor offset outside of cursor bitmap boundaries. Your code sets offset to `32,32`, while cursor size is 32px, resulting in hotspot being outside of cursor area.
In short: Not a bug, intended behavior. So intended SDL actually sets an error about that:
https://github.com/ennorehling/android-sdl/blob/79c3eb14acf256f744f1939c262fb923904e99ff/jni/SDL2/src/events/SDL_mouse.c#L554-L558
However it probably worth documenting and making check on Heaps side to inform user about this.

**Comment by infidel-** [comment]
Okay, I see your point. I've remembered why I have the offset - because the first cursor has a point in the corner and the other ones should be centered. But instead of using 16 as half-cursor size I used 32 as half-tile size. I guess DX/JS allow the cursor to be created in this case and SDL doesn't. It would probably be beneficial to automatically dump all SDL errors to stderr when -debug is set. That would show some hints to the programmer.

**Comment by Yanrishatum** [comment]
To dump SDL errors there have to be checks for SDL error everywhere it can occur on Heaps side, which is not something someone will bother with implementing, since they hadn't any need in it. ;) And also requires exposing methods of getting SDL errors from Haxe. (However exposing them is something I'd say is a good thing to have)

@trethaller I can prepare PR with checks on mouse size. Should it enforce in-bounds hotspot on DX/JS too or enforce it only for SDL? Also: Throw an error, or silently clamp values and trace the warning? (I'm inclined to SDL-only and throwing an error)
