### ISSUE TITLE
Use LocalFile system with HTML target

### ISSUE THREAD

**Issue by iOiurson** [HeapsIO/heaps#662]
Hi there !

I'm trying to learn Heaps, and i'd like to display images in the browser.
With HTML target, i get this error in the browser:
`"Local file system is not supported for this platform"`.

How do you work resources from your local filesystem using HTML target ?
Do you need the server to actually serve the resources, or is there a way to include them in the build ?

Thanks !

**Comment by ncannasse** [comment]
Files in the "res" directory are automatically included if you are using hxd.Res.initEmbed, and can be accessed using heaps resource system, see documentation here https://heaps.io/documentation/resource-management.html

**Comment by Yanrishatum** [comment]
Local FS is not possible on JS target due to JS target not being a system target (it can be, when used with Nodejs, but it's not something that is always available, e.g. regular browser)
For JS you can use either EmbedFS as Cannasse mentioned or pre-package files in a `.pak` file and  load it manually (`Res.initPak` won't work, because it's not implemented to work on JS).
Those are out-of-the-box solutions. There also my Manifest FS implementation, which is a bit finicky to get working (especially because I still haven't fixed readme to showcase proper way to init it): https://github.com/Yanrishatum/heeps#manifest-fs
It does expect files to be nearby the game index file, and obviously a server that serves them. Upside is that you only embed the manifest (list of files), and not base64-encoded files in your output JS files, resulting in insane file sizes.
