### ISSUE TITLE
Outline shader/filter uses wrong color on h2d.Text

### ISSUE THREAD

**Issue by zapparo** [HeapsIO/heaps#670]
.filter = new Outline(5, color);

There is some weird behavior on the h2d.Text. The outlines should use the same color.

![image](https://user-images.githubusercontent.com/18258502/64913071-dc470a00-d741-11e9-98e3-c18e3e9a289a.png)

Also changing the textcolor afects the applied color.

![image](https://user-images.githubusercontent.com/18258502/64913122-bb32e900-d742-11e9-89dc-fa47a4638009.png)

![image](https://user-images.githubusercontent.com/18258502/64913124-c84fd800-d742-11e9-80c5-633e05816cff.png)

**Comment by zapparo** [comment]
OK so it seems that outline works only if the textcolor is white otherwise is goes all over the place.

![image](https://user-images.githubusercontent.com/18258502/64913689-4a44fe80-d74d-11e9-830a-0c4f90937cfc.png)

![image](https://user-images.githubusercontent.com/18258502/64913691-516c0c80-d74d-11e9-8bfe-c31da3229d76.png)

![image](https://user-images.githubusercontent.com/18258502/64913693-5a5cde00-d74d-11e9-8f5b-aa974e8092c6.png)

**Comment by lbergman** [comment]
We use outline filter on a lot of text, and I recognize this issue, but cannot recall the exact details. 
Trying modifying blend mode on the objects to for example AlphaAdd and/or set alphaMultiplier of filter to false.

**Comment by Yanrishatum** [comment]
By the way, you can optimize outlining by using SDF fonts and custom SDF shader that would also add outline to the text in same pass as when it renders the glyphs themselves. It's far cheaper compared to h2d filters and should produce pretty accurate outline and also give all benefits of SDF fonts (scalability, nice looks when rotated). Main downside to be aware of if that glyphs should account for outline to avoid clipping and it may be tricky to replace SDF shader with custom one.

**Comment by lbergman** [comment]
What we do currently is to use SDF fonts and draw all our text to bitmap once, so cost of filters is not much issue, but SDF outlines would surely look better. I have been hoping to get some time to add support for that, but seemed like it could be a bit to tricky to be a quick fix for me at least :\

But for the blending issue in question I think we have not seen it since we switched to always drawing the text to bitmap, so that can be worth a try and anyway good practice to avoid the cost of running the filter on every frame.

**Comment by zapparo** [comment]
I am vaguely familiar with SDF fonts, but I have no idea how to draw the text to bitmap. Brand new to heaps.

**Comment by lbergman** [comment]
Display objects has a drawTo method to draw to a texture. You can then use that texture to create a Tile or Bitmap:
`final tex = new Texture(width, height, [TextureFlags.Target]);
object.drawTo(tex);
final tile = h2d.Tile.fromTexture(tex);
final bm = new h2d.Bitmap(tile);`

Put it in a utils class which renders text with style information to set color, alignment, outlines and shadow.

**Comment by lbergman** [comment]
Forgot to mention one quirk. Unless the text field is added to a scene, text doesn't appear. You can use an existing scene or create a temporary one and calling `scene.syncOnly(0)` before `drawTo`.

**Comment by Yanrishatum** [comment]
Please make a bug issue regarding that :) In theory Text should render just fine after creation without adding to scene. That is most likely caused by `rebuild` doing glyph init only if Text was allocated (added to active scene):
https://github.com/HeapsIO/heaps/blob/5dd5496c98f3fb260961416e89cd65c445da9b88/h2d/Text.hx#L150-L152
In theory it should init those here:
https://github.com/HeapsIO/heaps/blob/5dd5496c98f3fb260961416e89cd65c445da9b88/h2d/Text.hx#L120-L122
And I think bug is with `rebuild` setting `calcDone` to false regardless if it called `initGlyphs` or not (have to be moved to if block?).

**Comment by lbergman** [comment]
Actually I made an issue, and it was closed with a fix, which as I recall worked at the time. However when I should clean up and remove unnecessary stage usage the issue persisted.

https://github.com/HeapsIO/heaps/issues/358

**Comment by zapparo** [comment]
@lbergman I can confirm it's doesn't work without adding the text to a scene.

**Comment by Yanrishatum** [comment]
Minor update on reason behind invalid coloration:
This is caused due to filters being affect by `Drawable.color`, which is the case with all `Drawable` instances, meaning that this behavior is not `h2d.Text` exclusive (it's just Text uses this variable extensively and was easiest to spot). So, for example `Bitmap` with green tile and red outline filter won't show any outline if `color` was set to `0, 1, 0`. 
Current workaround: Use extra Object wrapper on which you apply outline filter and put Text inside of it.
I can't say if it's by design or overlooked bug. Solutions would be to:
* Disable filters being affected by `Drawable.color` globally.
* Attempt to reset `color` of Text when rendering with filters. Which is a dirty hack I have to say.
@ncannasse Comments?

**Comment by ncannasse** [comment]
It comes down to either applying the color pre filter or post filter. The
question only makes sense if there is both a color and a filter on the same
object. I guess having the color applied pre filter would maybe make more
sense ?

Le jeu. 7 nov. 2019 à 18:43, Pavel Alexandrov <notifications@github.com> a
écrit :
