### ISSUE TITLE
Zoom by mouse wheel

### ISSUE THREAD

**Issue by varadig** [HeapsIO/heaps#671]
like in the Sao example.

I tried on this way:
```
	override function update(dt:Float) {
		if (Key.isDown(Key.MOUSE_WHEEL_DOWN)) {
			trace("zoom out");
			this.s3d.camera.zoom += .01;
		}
		if (Key.isDown(Key.MOUSE_WHEEL_UP)) {
			trace("zoom in");
			this.s3d.camera.zoom -= .01;
		}
	}
```
but after some wheel up try to down:
```

Main.hx:67: zoom in
Main.hx:67: zoom in
Main.hx:67: zoom in
Main.hx:67: zoom in
Main.hx:67: zoom in
Main.hx:67: zoom in
Main.hx:67: zoom in
Main.hx:67: zoom in
Main.hx:67: zoom in
Main.hx:67: zoom in
Main.hx:67: zoom in
Main.hx:67: zoom in
Main.hx:67: zoom in
Main.hx:67: zoom in
Main.hx:67: zoom in
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
Main.hx:63: zoom out
Main.hx:67: zoom in
```

what is the proper way to zoom camera ?

**Comment by varadig** [comment]
and maybe example of free rotation like in sao exam.

**Comment by Yanrishatum** [comment]
Mouse wheel is special case for Key, as once it triggered, it always considered in "down" state due to internal works of the Key class, which makes sense, because it's not an on-off action, so more correct way to check if user did a scroll this frame would be using `Key.isPressed`. However! If user managed to perform multiple wheel turns between two ticks, you will receive only one "pressed" event. Proper solution is to add event handler and handle wheel events directly either via `Window.addEventTarget` or `Scene.addEventListener`. Both are instance methods, not static ones. I recommend using second one, because first one is utilized by scenes.

**Comment by varadig** [comment]
Ok, now it's working

```
	override function update(dt:Float) {
		if (Key.isPressed(Key.MOUSE_WHEEL_DOWN)) {
			trace("zoom out");
			this.s3d.camera.zoom += .01;
		}
		if (Key.isPressed(Key.MOUSE_WHEEL_UP)) {
			trace("zoom in");
			this.s3d.camera.zoom -= .01;
		}
	}
```

but what about the mouse wheel delta?
In the sao example the zoom is smooth, and depend on the scroll sensitivity.

**Comment by Yanrishatum** [comment]
`Key` does not expose wheel delta as it's only purpose is to tell if button was pressed, held or unpressed (and in case of mouse wheel - if it was scrolled or not, not how much it was scrolled).
As I said before - if you want to properly implement support for mouse wheel including wheel delta - you have to use `Interactive.onWheel`, which would work only if mouse is over the interactive, or `Window.addEventTarget` / `Scene.addEventListener`. And for event callbacks, you need to check that event type is of `EWheel`. Then you would be able to retrieve the `wheelDelta` variable from event instance.
You also need to be aware that Interactives can interrupt the callback chain in Scene and you are not guaranteed to have your callback invoked, because non-propagating Interactive was under mouse.

In advance - adding wheelDelta to Key faces a few problems:
First, between two ticks there is a chance that user made more than one wheel turn, resulting in 2 or more `EWheel` events. When listening - you'd get those in order, with a constant delta, however Key would need to accumulate those. Second, Key is event-driven, using `Window.addEventTarget`, and does not perform any does not have an update loop. Key states are stored as either positive or negative frame number at which it was triggered, meaning that there should be check during accumulation to discard previous frame wheel delta. 
I mean, it's pretty easy to add, but that depends if Cannasse and other main devs would approve of such thing, and there is solid reasoning in need of exposing the wheelDelta in Key.

**Comment by varadig** [comment]
@Yanrishatum, thanks for clarify this.

**Comment by varadig** [comment]
Just one more question..... somebody can show me, where is the interaction of the [Sao](https://github.com/HeapsIO/heaps/tree/master/samples) example?
I really can't see any of Interactive or event listener of scene/window

**Comment by Yanrishatum** [comment]
Pay attention to source code - it using stock camera controller:
https://github.com/HeapsIO/heaps/blob/9a8add2ebc2e3a663e6042a80d9361f87ecab9fc/samples/Sao.hx#L105-L108

**Comment by varadig** [comment]
That's it is!!! thanks
