### ISSUE TITLE
Over backward compatible behavior

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/heaps#675]
Before #537, the order of events was:
- over element A
- out element A
- over element B

Now it's:
- over element A
- over element B (read propagate result)
- out element A (if propagate = false)

As a result, tooltip systems are slightly more difficult to implement because you need to retain which tooltip belongs to which element in order to properly

Previous behavior:
- over element A : display A tooltip
- out element A : clear tooltip
- over element B : display B tooltip

And also, since this breaks backward compatibility, having a single "singleOver : Bool" flag to turn on to restore previous behavior would be a nice addition.

**Comment by Yanrishatum** [comment]
I agree that `EOut` should be fired before `EOver`, but I'm not sure that can be implemented. Currently, propagation only known after `EOver` is handled by Interactive so firing `EOut` beforehand can cause inconsistent behavior, unless there would be an extra method (`shouldPropagate(event)`) that just says if event type would propagate.
E.g.: Instead of firing `EOver`, it would call `shouldPropagate(EOver)`, and fill over array accordingly, marking which Interactives need to be overed, then, after `EOut` were fired, it would fire `EOver`.
But then that event would need to be handled by other places where `event.propagate` is checked and will cause edge case of ignoring it in case of overs. That also would break event cancelling in case `EOver` would cancel out. 
And `singleOver` seem like a crutch, honestly.
My only idea is to separate propagation from `Event` instance, and move it to `shouldPropagate(e:Event):Bool` method.

**Comment by ncannasse** [comment]
One way would be to ignore event.cancel / propogate on EOver, and instead consider only the one in EMove . That would somewhat help with #566 as well, since we would not have to check propagateEvents but instead keep checking the EMove/ECheck propagate (in case it changes)

In that definition, EOver/EOut cannot really be canceled/propagated anymore, they are just a consequence of EMove, which seems accurate to me, unless you see any show stopper.

**Comment by ncannasse** [comment]
Ping @trethaller for insight

**Comment by Yanrishatum** [comment]
So, as I understood, it would work as:
1. Handle `EMove`: Read propagation; Skip to 3 if cancelled.
2. Mark Interactive as overed if it wasn't already overed.
3. If `propagate` or `cancel` - repeat 1-3 for next Interactive
4. Issue `EOut` on all Interactives that aren't under mouse or cancelled their EMove.
5. Issue `EOver` on all Interactives that were marked overed this frame.

Correct?

Now onto issues/behavior changes:
* There would be a need for a separate list of Interactives that were overed this frame, compared to current approach of calling EOver instantly, and EOut on ones that outside of new over list size. Also extra loop over overed list after EOut loop.
* Making EOut impossible to cancel I see as a positive, because cancelling it does not make any sense. That Interactive already won't receive EMove or ECheck, but would be asked "are you ready to relieve your overed status already?" each frame, which is silly. There's startDrag/stopDrag for that :)
* On other hand, inability to cancel EOver should be documented as to not produce confused users who would come to discord/forums/issues asking why it still overed, even if he cancelled the event. Entire thing should be documented as to make it clear what can and cannot be done in that case.

Now that you mentioned EMove, there's another slightly illogical behavior. When overing, it would cause EMove first and only then EOver, while by logic it should cause it in inverse order (EOver -> EMove, not EMove -> EOver).

**Comment by ncannasse** [comment]
> Correct?

Yes

> * There would be a need for a separate list of Interactives that were overed this frame, compared to current approach of calling EOver instantly, and EOut on ones that outside of new over list size. Also extra loop over overed list after EOut loop.

We can have two Arrays :
- currently hover
- hover candidates (this frame)
Both arrays are sorted (topmost first)
We could walk hover candidates (starting from the last) and lookup in current hover list if it's already there, a quick match is to look at topmost and eventually insert it there (reorder if there was a swap in priority).

> * Making EOut impossible to cancel I see as a positive, because cancelling it does not make any sense. That Interactive already won't receive EMove or ECheck, but would be asked "are you ready to relieve your overed status already?" each frame, which is silly. There's startDrag/stopDrag for that :)
> * On other hand, inability to cancel EOver should be documented as to not produce confused users who would come to discord/forums/issues asking why it still overed, even if he cancelled the event. Entire thing should be documented as to make it clear what can and cannot be done in that case.

Agree. I was thinking throwing if we set EOver cancel = true, but that would not be good as one might cancel all events outside of Interactive shape without checking for EOver or not.

> Now that you mentioned EMove, there's another slightly illogical behavior. When overing, it would cause EMove first and only then EOver, while by logic it should cause it in inverse order (EOver -> EMove, not EMove -> EOver).

I don't think that's much of an issue, this could maybe be fixed separately by triggering ECheck if the element is not currently overred and EMove either.
