### ISSUE TITLE
h2d.Text updates glyphs very eagerly

### ISSUE THREAD

**Issue by Simn** [HeapsIO/heaps#688]
```haxe
	function set_text(t : String) {
		var t = t == null ? "null" : t;
		if( t == this.text ) return t;
		this.text = t;
		rebuild();
		return t;
	}

	function rebuild() {
		calcDone = false;
		if( allocated && text != null && font != null ) initGlyphs(text);
		onContentChanged();
	}
```

This causes glyph rebuilding on every text change. When using Text in a way that causes many `set_text` calls (e.g. for a logging component), we end up with a huge overhead (multiple seconds in my case).

I think `rebuild` should instead set some `rebuildGlyph` flag which is then checked by... something else. I tried this in `sync` which seems to work well:

```haxe
	override function sync(ctx:RenderContext) {
		super.sync(ctx);
		if (rebuildGlyphs) {
			initGlyphs(text);
			rebuildGlyphs = false;
		}
	}
```

Not sure if that's the ideal place to check this though.

**Comment by Simn** [comment]
One concern is the `onContentChange()` call which would then happen before the rebuild is finished. This likely requires some more `rebuildGlyphs` checks in other places.

**Comment by Yanrishatum** [comment]
I agree that eager `initGlyphs` on any text change is excessive (however I never experienced issues with it, because I usually construct entire string and assign it only once).
There's already a flag that marks glyphs invalid - `calcDone`. However it is used to also calculate sizes with textWidth/textHeight/getBoundsRec() which marks it to `true`.
Two ways:
* Accessing `textWidth`, `textHeight` and `getBoundsRec` will trigger glyph cache rebuild if Text is already allocated. Changes to code would be minimal.
* As you propose - adding `rebuildGlyphs` flag (or if we want to avoid extra field - make calcDone an Int flag field which would hold both `calcDone` and `rebuildGlyphs`) and mark it on `rebuild`, removing it only when actual glyph graphics are used (e.g. on `draw` or `sync`). 

The glyphs are internal structure and are not expected to be accessed outside, so not initializing it until the moment it is required makes sense, as nothing is supposed to access it beforehand.

**Comment by ncannasse** [comment]
If we want to do that, we will need to separate text parsing/validation (only in htmltext) that should be eagerly performed for reasons mentioned in #762, from actual glyphs rebuild / text layout.

**Comment by Simn** [comment]
That makes sense to me. I expect validation to be fast so even if there are multiple updates it shouldn't affect performance significantly.
