### ISSUE TITLE
HtmlText delayed validation

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/heaps#762]
The problem with recent changes in Text/HtmlText which delays the initGlyphs is that formatting errors (such as invalid xml, but could be also anything involving font error or loading image error) now only occurs at display time, making it hard to debug because your stack is no longer the place the text is set but a generic in-render stack.

I think that's problematic, maybe we should have this behavior be opt-in (default false).

Ping @Yanrishatum

**Comment by Yanrishatum** [comment]
Isn't that goes in the opposite direction of #688? Also I'm not sure which changes you refer to, as #695 was not merged to master, and rework PR did not change at which point Text causes glyph init. E.g. on `sync()`, on actions that cause `rebuild()` (inc. text change) and on `draw` (in order to ensure that glyphs are initalized, when trying to draw fresh Text instance onto texture without having called `onAdd()`).
I can make `eagerValidation` flag, that would cause simplified pass that would only go trough parsing XML and fetching the font/images, as that (ideally) should be the only fail-points when rendering HtmlText. That would impact performance, but not to a degree of causing full-on rebuild. (And if implemented in a way that `rebuild` is aware of that flag and uses precached parsed data - may mitigate some of that impact).

**Comment by ncannasse** [comment]
Yes that's opposite to #688 
As for the change, we got some bug reports with the following stack:

```
h2d.HtmlText.addNode (h2d/HtmlText.hx line 590)
h2d.HtmlText.initGlyphs (h2d/HtmlText.hx line 144)
h2d.Text.rebuild (h2d/Text.hx line 141)
h2d.Text.updateConstraint (h2d/Text.hx line 345)
h2d.Text.set_maxWidth (h2d/Text.hx line 332)
ui.win.$Notify.__constructor__ (ui/win/Notify.hx line 60)
```

But now that I think about it that might actually be a bug due to splitText (when changing maxWidth), not due to setting the text itself.

**Comment by Yanrishatum** [comment]
Updated #695 with HtmlText eager validation.
As for that crash, it may be related to #761 somehow, as crash is clearly happens because it increases metric caret too many times somewhere, causing it to go out of bounds, hence - null pointer on the metric. I would need to see at what text this happens, however.
