### ISSUE TITLE
[feature/guide/example request]: gamma correct 2d rendering

### ISSUE THREAD

**Issue by farteryhr** [HeapsIO/heaps#766]
yes things have been wrong for so long... and there seems not much attention on this point on 2D games. but 2D games with color blending, blurring, even just anti-aliasing, etc. still look dark "as always did".

http://love2d.org/wiki/love.graphics.isGammaCorrect

many details are in Notes, and yes they're all work to be done.

but since there is already PBR rendering in h3d, that's already many steps ahead and much could be reused. i think we could have this documented and made into examples, so that 2D games could be made gammacorrect more easily too?

btw something i feel weird is that since love2d 11.0, all colors passed as arguments (literals, though they don't have to be) are changed from 0-255 integers to floating point numbers ranging 0-1, but as stated on the wiki page, they're still considered sRGB and will be converted to linear when `gammacorrect` is set to true.
conceptually i think it's better to limit sRGB in Int and regard all floating point numbers linear... just my wish..

**Comment by ncannasse** [comment]
In order to have gamma correct rendering without loss of precision you need:

- a shader that does transform your RGB to sRGB, this could be done in h3d/shader/Base2d upon texture.get
- use a RGBA16F accumulation buffer instead of RGBA8 (to prevent loss of precision)
- a post process that goes from sRGB to RGB again

Nothing very hard, but would still takes a bit of time to put in place correctly, and deal with specific cases such as filters.
