### ISSUE TITLE
Large Buffer

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/heaps#839]
Now that 32 bit indexes are quite the norm, we should review our vertex buffer splitting strategy.
- remove the whole ManagedBuffer / Buffer difference (inherited from flash era were we would allocate large managed then allocate into them) 
- keep a single 32 bit "triIndexes" + "quadIndexes" that grows upon requests
This should reduce draw calls for large batches/meshes (currently auto split at 64K)

**Comment by Yanrishatum** [comment]
There also should be support for legacy 16-bit index buffers, since HMD stores them in that format. And same HMD should also be updated to support 32-bit buffers. I'm not sure if it was really the case, but there was someone in Discord, who managed to make an FBX so big, that it managed to crash the converter, and I suspect it was caused by index buffer being 16-bit.

**Comment by ncannasse** [comment]
Sure, we'll keep 16 bit buffers compat, and I'll look into HMD/32 bits

**Comment by ncannasse** [comment]
Note : HMD does support 32 bit indexes for some time now.

**Comment by ncannasse** [comment]
Done in recent commit
