### ISSUE TITLE
[h2d.Layers] Inconsistent addChildAt and getChildIndex

### ISSUE THREAD

**Issue by kevinresol** [HeapsIO/heaps#862]
```haxe
class Main extends hxd.App {
	override function init() {
		new h2d.Object(s2d);
		new h2d.Object(s2d);
		
		var obj = new h2d.Object();
		s2d.addChildAt(obj, 1);
		trace(s2d.getChildIndex(obj));
	}
	static function main() {
		new Main();
	}
}
```

This will print 2 but expected 1, because we called addChildAt 1

**Comment by ncannasse** [comment]
addChildAt for layers use a layer number.

Le jeu. 30 juil. 2020 à 08:47, Kevin Leung <notifications@github.com> a
écrit :

**Comment by kevinresol** [comment]
I assume the following assertion should always hold for any h2d.Object

```haxe
container.addChildAt(obj, x);
container.getChildIndex(obj) == x;
```

A child class overriding the parent class changing the behaviour is a violation of the [Liskov Substitution Principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle)

**Comment by ncannasse** [comment]
Sure, it's quite an old "feature" that is not much actually used.
Before changing that thought it would require we run a few tests on our games NG and DB.

**Comment by Yanrishatum** [comment]
Fixing `Layers.addChildAt` would cause a rather major breaking change, but I agree that its behavior is not obvious at a glance.

Also I don't agree that sample with Object always holds:
```haxe
var container = new h2d.Object();
var child = new h2d.Object();
container.addChildAt(child, 10);
container.getChildIndex(child); // Yields 0
```
Since index is being clamped `0 <= index <= children.length`.

I have to note, that if `addChildAt` is not changed from `Object`, that would cause Layers to break in the following sample:
```haxe
container.add(child1, 0);
container.add(child2, 1);
container.addChildAt(child1, 5);
```
This sample would cause `child1` to move onto layer 2, and `child2` to layer 1.
That raises a question: Should `addChildAt` account for the layers? I think yes. But I also would propose another feature to Layers: `public var defaultLayer:Int = 0` that would override the default layer to which `addChild` and `addChildAt` add to, instead of always adding to layer 0. That also would allow adding to other layers with `new Object(layers)`.
On top of that `getChildIndex` should account for layers as well.

In summary, what I propose:
* Add `defaultLayer:Int = 0` that would dictate to which layer `addChildAt` adds. 
* `add` method would take 3 arguments - child object, layer and an in-layer index.
* `addChildAt` would become a shorthand for `add(child, defaultLayer, index)`.
* `getChildIndex` would return an index within the layer.
* Add a `getChildAtLayer` method that would act same way as `getChildAt` but with specific layer instead of default one.
* `getChildAt` would use current default layer.

If the `defaultLayer` implementation is vetoed, changes would still remain the same with defaultLayer being a constant 0. :)

This way, Layers would isolate all information regarding how objects are stored internally (i.e. trough single `children` list) and each layer can be treated individually, along with swapping children positions with `addChildAt`.

**Comment by Yanrishatum** [comment]
I've implemented the fix, and now it's up to Shiro to check that they use `add` instead of `addChildAt` and such before merge. ;)
