### ISSUE TITLE
Correct Fixed Timestep Setup

### ISSUE THREAD

**Issue by bojjenclon** [HeapsIO/heaps#878]
I'm trying to setup a fixed timestep update loop so movement works the same regardless of the running FPS, but I'm running into some issues. My first approach was thus:

Per: https://gafferongames.com/post/fix_your_timestep/

```haxe
override public function update(dt : Float)
  {
    _accumulator += dt;
    while (_accumulator >= _fixedStep)
    {
      // Update calls

      _accumulator -= _fixedStep;
    }
}
```

However, I noticed inputs weren't accurate. It seems this throws off the way events are handled, so things like key events won't properly be updated during the loop.

So what's the proper way in Heaps to make movement consistent across FPS?

**Comment by rcstuber** [comment]
Logically my assumption would be that you should just update your game logic (i.e. objects position) within the fixed time-step loop, not calling the engines loop in there. The engine loop should be the outer loop. Haven‘t tested it though.

**Comment by ncannasse** [comment]
The problem is that depending on the screen refresh rate, you will get lagish frames or skipped frames updates.
Either you use a very small _fixedStep and ends up doing several of these calls per "real frame" - which will have a high CPU cost, or you simply use dt for all your movements (for instance  `x += speed * dt`). Animation update time is currently using the later for both 2D and 3D (see hxd.App setElapsedTime usage)
