### ISSUE TITLE
Domkit Build failure

### ISSUE THREAD

**Issue by ialak** [HeapsIO/heaps#909]
https://github.com/HeapsIO/heaps/blob/master/samples/Domkit.hx#L9

This line report Unsupported code block
![image](https://user-images.githubusercontent.com/3145698/99218460-7d819280-2815-11eb-805c-c12f4a4aac4c.png)

**Comment by Yanrishatum** [comment]
This is due to Cannasse deciding to drop plaintext support for whatever reason, see https://github.com/HeapsIO/domkit/issues/21
But sample was not updated to reflect that change, so I shall summon @ncannasse to fix regression in samples over a breaking change in library. :) 
(also I personally think that using plaintext only for control structures is not good idea and dropping support for plaintext limits the usability of the lib a lot, and for example with time constraints of jams - plaintext is the way to go, hence using domkit in such circumstances is ill-advised)

**Comment by ialak** [comment]
oh, thinks :) , I also think the structure is more reasonable, but timely updates are more important
