### ISSUE TITLE
Creating model instance when fxb was loaded from bytes fails

### ISSUE THREAD

**Issue by olichose123** [HeapsIO/heaps#910]
With a simple unmodified cube created in blender even without any texture called model.fbx in the res folder, the following reproduction code fails. If you comment `var obj = cache.loadModel(modelFromBytes);` and uncomment the following line, the model loads correctly, but this static method of loading assets might not be effective when files are defined externally (like for moddable games).

```haxe
class Main extends hxd.App
{
    public static function main():Void
    {
        new Main();
    }

    override private function init():Void
    {
        hxd.Res.initLocal();

        var modelFromBytes = hxd.res.Any.fromBytes("", 
        sys.io.File.getBytes("res/model.fbx")).toModel();

        var modelFromRes = hxd.Res.model;

        var cache = new h3d.prim.ModelCache();
        
        var obj = cache.loadModel(modelFromBytes);
        //var obj = cache.loadModel(modelFromRes);

        s3d.addChild(obj);
    }
}
```

The error is a ValueException but seems to originate from "Invalid HMD header" at line 132 in hmd.Reader. The first three letters of the header are `Kay` instead of HMD in my file, but it still works with hxd.Res loading.

The result is similar with manual loading defined in the [documentation](https://heaps.io/documentation/fbx-models.html)
```haxe
function testManualLoading():Void
{
    var modelFromBytes = hxd.res.Any.fromBytes("res/model.fbx", 
    File.getBytes("res/model.fbx")).toModel();
    var modelFromRes = hxd.Res.model;

    var lib = modelFromBytes.toHmd();
    //var lib = modelFromRes.toHmd();

    var obj = lib.makeObject();
    s3d.addChild(obj);
}
```
The code above fails with the same error unless modelFromRes is used.

The model is the default blender cube, without texture, with FBX Units scale, Z up, -Y forward. I pretty much opened a blender scene then exported the cube with the settings specified in the documentation.

**Comment by olichose123** [comment]
After some more research, it seems that even without a props.json in res, there is some kind of conversion going on.
* `var model:Model = hxd.Res.lowpoly;` works as a static solution
* `var model:Model = hxd.Res.loader.load("lowpoly.fbx").toModel();` works as a dynamic solution, but still limited to the res/ folder
* `var model:Model = hxd.res.Any.fromBytes("", File.getBytes("res/lowpoly.fbx")).toModel();` does not work, as the model is somehow not a HMD
* And finally:
```haxe
var b = hxd.Res.loader.load("lowpoly.fbx").entry.getBytes();
var model = hxd.res.Any.fromBytes("", b).toModel();
```
does not work either, for the same reason as above, but we still used a Loader to get the data.

After some more research while writing the first part:
It seems that the solution is to create a new hxd.res.Loader for every folder you want to access. I thought I was limited to res/. Though I'm curious as to why there is some kind of conversion behind the scene of fbx models while I can easily load other objects like images and sounds from haxe.io.File.getBytes(). Shouldn't that conversion NOT happen if no props.json is defined?

**Comment by Yanrishatum** [comment]
Please don't fight the resource management system. If you want to dynamically load mods, you can just add extra folders to FileSystem if you're using LocalFileSystem, it's not limited to one directory. Or use MultiFileSystem. 

And conversion is here to convert from FBX to internal HMD format that provides far faster model loading and was mandatory at the very least because initially only text FBX were supported, and those are insanely big raw text files that would not be good to parse at runtime. Even after introduction of binary FBX support - format has to be processed a fair bit to make it usable by the engine.

**Comment by ncannasse** [comment]
The problem here is that hxd.res.Any.fromBytes is not tight to any filesystem, and thus doesn't really know where to cache & store the converted files. So yes, you cannot use this method, but you can create another LocalFileSystem and use MultiFileSystem as Pavel suggested.

As for conversions, yes FBX to HMD is mandatory and we don't support direct FBX loading anymore.

**Comment by olichose123** [comment]
Thanks for the clarification. I'll adjust my projects to make better use of the resource management system. Still, I think some kind of error should be thrown in such a context where Any.fromBytes().toModel() is called. Handling data as bytes IS a use case, among other when storing data with hxbit or building more complex data structures (an array of models saved as bytes, etc.).

Though I understand the conversion from fbx to hmd is logically necessary, the documentation on props.json implied you needed to specify the conversion otherwise it was done on loading, thus my questions.

Still, thanks a lot for your answers to both of you!
