### ISSUE TITLE
heaps does not compile with current haxe lib

### ISSUE THREAD

**Issue by neshume** [HeapsIO/heaps#989]
It seems the API setClipboardText/getClipboardText is missing from current haxe lib

system.hl.hx does not compile .

cheers,

neshume

**Comment by lumodon** [comment]
Running into same problem myself for a few days now.

Has to do with `hlsdl` in `haxe/lib/hlsdl`

Haxelib install only offers up to `1.10.0` but the git for HashLink shows these new functions in source

I tried copying the Windows binary HashLink offers and pasting its' into `haxe/lib/hlsdl/1,12,0/` and then modifying the tutorial's `-lib hlsdl:1.12.0` line in the `compile.hxml` and the contents in `haxe/lib/hlsdl/.current` to `1.12.0` but then I just get the different bug:
```sh
src\module.c(352) : FATAL ERROR : Failed to load library ?sdl.hdll
```

Don't know where to obtain this `sdl.hdll` - didn't see it in HashLink, Haxe, nor Heaps repos
Must be a build-output but couldn't find anything useful when google searching `("hdll" OR "sdl.hdll") -DeadCells -game -games -steam`

I've tried to obtain visual studio 2013 or 2015 or something in order to compile but could not figure out how to download Visual Studio.

Even tried changing target to 2019 just to see if it'd work but could not get HashLink to compile with the latest [SDL Dev Library](https://www.libsdl.org/download-2.0.php)

**Comment by neshume** [comment]
I am an engine builder + game developer .. I work with c++/rust whatever all the time for many years now .. the point of working with haxe is to leave all this behind .. and the point of using an open source engine is the community and live sign .. it seems nobody cares that the main master branch does not compile with latest haxe ! I just forked and disabled the infected api's in heaps hxd :o)  you work with what you have :o) and if nobody cares .. you care enough to keep this going .. messing with sdl dll's is not what I am looking for when walking the haxe path .. but again I could be wrong .. no complaints just work ;o). I think the minimum is compile ability with latest haxe .. bugs are fine but build heaps with haxe pull request not merged (at least not public) inside haxe is like an open source finger in your eye.. sorry for the analogy. Its not like you can't go around it .. its trust.

**Comment by neshume** [comment]
BTW @lumodon .. feel free to use my fork .. it should compile just fine .. tell me if this works for you (my discord https://discord.gg/XG553zWt)

fork : https://github.com/neshume/heaps

**Comment by rcstuber** [comment]
Maybe a new Hashlink release (1.12.0) to Haxelib would be the better solution @ncannasse 😜

**Comment by ncannasse** [comment]
Actually this fix also requires a new Haxe Release for not-SDL platforms
(DirectX) :')

**Comment by rcstuber** [comment]
As always, you outsmart me 😄
